"""
Confidence / abstention analysis for the frozen 55/45 CatBoost + GRU ensemble.

Uses validation predictions already generated by:
    analyze_binary_complementarity.py

No model retraining.
No test-set usage.

Question:
    Does ensemble accuracy improve when we only act on
    higher-confidence predictions?
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.metrics import (
    accuracy_score,
    f1_score,
)


# ============================================================
# PATHS
# ============================================================

PROJECT_ROOT = Path(__file__).resolve().parents[2]

PREDICTIONS_FILE = (
    PROJECT_ROOT
    / "reports"
    / "binary_catboost_gru_validation_predictions_v1.parquet"
)

REPORTS_DIR = (
    PROJECT_ROOT
    / "reports"
)


# ============================================================
# CONFIGURATION
# ============================================================

# These are minimum predicted probabilities for the chosen
# direction. For a probability of:
#
# 0.50 -> confidence = 0.50
# 0.60 -> confidence = 0.60
# 0.40 -> confidence = 0.60
#
# Therefore the analysis is symmetric for UP and DOWN.
CONFIDENCE_THRESHOLDS = [
    0.50,
    0.55,
    0.60,
    0.65,
    0.70,
    0.75,
    0.80,
]


# ============================================================
# MAIN
# ============================================================

def main():

    print("=" * 70)
    print("ENSEMBLE CONFIDENCE / ABSTENTION ANALYSIS")
    print("=" * 70)

    if not PREDICTIONS_FILE.exists():
        raise FileNotFoundError(
            f"Validation prediction file not found:\n"
            f"{PREDICTIONS_FILE}"
        )

    print(
        f"\nLoading validation predictions:\n"
        f"{PREDICTIONS_FILE}"
    )

    df = pd.read_parquet(
        PREDICTIONS_FILE
    )

    print(
        f"Validation prediction rows: "
        f"{len(df):,}"
    )

    required_columns = [
        "symbol",
        "catboost_probability_up",
        "gru_probability_up",
        "catboost_target",
    ]

    missing = [
        column
        for column in required_columns
        if column not in df.columns
    ]

    if missing:
        raise ValueError(
            f"Missing required columns:\n{missing}"
        )

    # --------------------------------------------------------
    # Reconstruct frozen 55/45 ensemble
    # --------------------------------------------------------

    df = df.copy()

    df["ensemble_probability_up"] = (
        0.55
        * df["catboost_probability_up"]
        +
        0.45
        * df["gru_probability_up"]
    )

    df["ensemble_prediction"] = (
        df["ensemble_probability_up"]
        >= 0.50
    ).astype(np.int64)

    df["target"] = (
        df["catboost_target"]
        .astype(np.int64)
    )

    # Confidence is distance from a neutral 50/50 prediction.
    #
    # 0.50 probability -> confidence 0.50
    # 0.60 probability -> confidence 0.60
    # 0.40 probability -> confidence 0.60
    df["confidence"] = np.maximum(
        df["ensemble_probability_up"],
        1.0 - df["ensemble_probability_up"],
    )

    # --------------------------------------------------------
    # Full validation baseline
    # --------------------------------------------------------

    y_true = df["target"].to_numpy()

    full_prediction = (
        df["ensemble_prediction"]
        .to_numpy()
    )

    full_accuracy = accuracy_score(
        y_true,
        full_prediction,
    )

    full_macro_f1 = f1_score(
        y_true,
        full_prediction,
        average="macro",
    )

    print("\nFull validation ensemble:")
    print(
        f"Accuracy : {full_accuracy:.6f}"
    )
    print(
        f"Macro-F1 : {full_macro_f1:.6f}"
    )

    # --------------------------------------------------------
    # Confidence sweep
    # --------------------------------------------------------

    results = []

    for threshold in (
        CONFIDENCE_THRESHOLDS
    ):

        selected_mask = (
            df["confidence"]
            >= threshold
        )

        selected = df.loc[
            selected_mask
        ]

        n_selected = len(selected)

        coverage = (
            n_selected / len(df)
            if len(df) > 0
            else 0.0
        )

        if n_selected == 0:

            results.append(
                {
                    "confidence_threshold":
                        threshold,
                    "samples":
                        0,
                    "coverage":
                        0.0,
                    "accuracy":
                        np.nan,
                    "macro_f1":
                        np.nan,
                    "accuracy_gain_vs_full":
                        np.nan,
                }
            )

            continue

        selected_y = (
            selected["target"]
            .to_numpy()
        )

        selected_prediction = (
            selected["ensemble_prediction"]
            .to_numpy()
        )

        accuracy = accuracy_score(
            selected_y,
            selected_prediction,
        )

        macro_f1 = f1_score(
            selected_y,
            selected_prediction,
            average="macro",
        )

        results.append(
            {
                "confidence_threshold":
                    threshold,
                "samples":
                    n_selected,
                "coverage":
                    coverage,
                "accuracy":
                    accuracy,
                "macro_f1":
                    macro_f1,
                "accuracy_gain_vs_full":
                    accuracy - full_accuracy,
            }
        )

    results_df = pd.DataFrame(
        results
    )

    # --------------------------------------------------------
    # Print results
    # --------------------------------------------------------

    print("\n" + "=" * 70)
    print("CONFIDENCE SWEEP")
    print("=" * 70)

    display_df = results_df.copy()

    display_df["coverage"] = (
        display_df["coverage"]
        * 100
    )

    display_df["accuracy"] = (
        display_df["accuracy"]
        * 100
    )

    display_df["macro_f1"] = (
        display_df["macro_f1"]
        * 100
    )

    display_df[
        "accuracy_gain_vs_full"
    ] = (
        display_df[
            "accuracy_gain_vs_full"
        ]
        * 100
    )

    print(
        display_df.to_string(
            index=False,
            formatters={
                "coverage":
                    lambda x: f"{x:.2f}%",
                "accuracy":
                    lambda x: f"{x:.2f}%",
                "macro_f1":
                    lambda x: f"{x:.2f}%",
                "accuracy_gain_vs_full":
                    lambda x: f"{x:+.2f} pp",
            },
        )
    )

    # --------------------------------------------------------
    # Find useful operating point
    #
    # We require at least 10% coverage so we don't
    # accidentally select a tiny number of predictions.
    # --------------------------------------------------------

    viable = results_df[
        results_df["coverage"] >= 0.10
    ].copy()

    if len(viable) > 0:

        best = viable.loc[
            viable["accuracy"].idxmax()
        ]

        print(
            "\nBest validation accuracy "
            "with >=10% coverage:"
        )

        print(
            f"Confidence threshold: "
            f"{best['confidence_threshold']:.2f}"
        )

        print(
            f"Coverage: "
            f"{best['coverage'] * 100:.2f}%"
        )

        print(
            f"Accuracy: "
            f"{best['accuracy'] * 100:.2f}%"
        )

        print(
            f"Macro-F1: "
            f"{best['macro_f1'] * 100:.2f}%"
        )

        print(
            f"Gain vs full ensemble: "
            f"{best['accuracy_gain_vs_full'] * 100:+.2f} pp"
        )

    # --------------------------------------------------------
    # Per-coin confidence analysis
    # --------------------------------------------------------

    per_coin_results = []

    for symbol in sorted(
        df["symbol"].unique()
    ):

        symbol_df = df[
            df["symbol"] == symbol
        ]

        for threshold in (
            CONFIDENCE_THRESHOLDS
        ):

            selected = symbol_df[
                symbol_df["confidence"]
                >= threshold
            ]

            if len(selected) == 0:
                continue

            selected_y = (
                selected["target"]
                .to_numpy()
            )

            selected_prediction = (
                selected[
                    "ensemble_prediction"
                ]
                .to_numpy()
            )

            per_coin_results.append(
                {
                    "symbol":
                        symbol,
                    "confidence_threshold":
                        threshold,
                    "samples":
                        len(selected),
                    "coverage":
                        len(selected)
                        / len(symbol_df),
                    "accuracy":
                        accuracy_score(
                            selected_y,
                            selected_prediction,
                        ),
                    "macro_f1":
                        f1_score(
                            selected_y,
                            selected_prediction,
                            average="macro",
                        ),
                }
            )

    per_coin_df = pd.DataFrame(
        per_coin_results
    )

    # --------------------------------------------------------
    # Save
    # --------------------------------------------------------

    REPORTS_DIR.mkdir(
        parents=True,
        exist_ok=True,
    )

    sweep_path = (
        REPORTS_DIR
        / "binary_ensemble_confidence_sweep_v1.csv"
    )

    results_df.to_csv(
        sweep_path,
        index=False,
    )

    per_coin_path = (
        REPORTS_DIR
        / "binary_ensemble_confidence_per_coin_v1.csv"
    )

    per_coin_df.to_csv(
        per_coin_path,
        index=False,
    )

    metadata = {
        "ensemble_weights": {
            "catboost": 0.55,
            "gru": 0.45,
        },
        "full_validation_accuracy":
            float(full_accuracy),
        "full_validation_macro_f1":
            float(full_macro_f1),
        "thresholds":
            CONFIDENCE_THRESHOLDS,
        "note":
            "Confidence analysis uses validation predictions only.",
        "definition":
            "confidence = max(P(UP), P(DOWN))",
    }

    metadata_path = (
        REPORTS_DIR
        / "binary_ensemble_confidence_metadata_v1.json"
    )

    with open(
        metadata_path,
        "w",
        encoding="utf-8",
    ) as file:

        json.dump(
            metadata,
            file,
            indent=2,
        )

    print("\nReports saved:")
    print(sweep_path)
    print(per_coin_path)
    print(metadata_path)


if __name__ == "__main__":
    main()